#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""Delete fake SSM Resource Data Sync inventory generated by
generate_test_data.py.

Deletes only objects whose key matches `i-deadbeef*` under the four
AWS:* prefixes for the given account/region. Real SSM inventory
(genuine i-0abc... IDs) is untouched. The instance ID format
`i-deadbeef########` is what generate_test_data.py produces — see
the comment on make_instance_id there for why we use real-EC2-format
hex rather than an `i-test` prefix.

If the DataSync bucket has versioning enabled, this script deletes
each version individually using delete-object (one API call per
object) so we never hit the DeleteObjects 1000-entry / MalformedXML
issue that bit the dashboard's bucket teardown.

Usage:
    python3 delete_test_data.py \\
        --bucket resource-datasync-org \\
        --account-id 528314645158 \\
        --region us-east-2 \\
        --profile default
"""

import argparse
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

import boto3
from botocore.config import Config

INVENTORY_TYPES = [
    'AWS:PatchSummary',
    'AWS:InstanceInformation',
    'AWS:ComplianceItem',
    'AWS:Tag',
]

TEST_KEY_MARKER = 'deadbeef'  # generate_test_data.py uses i-deadbeefXXXXXXXX as the fake instance ID format

PRINT_EVERY = 100


def list_test_object_versions(s3, bucket: str, prefix: str):
    """Yield (key, version_id) tuples for objects whose key contains
    the test marker. Walks all versions plus all delete-markers."""
    paginator = s3.get_paginator('list_object_versions')
    for page in paginator.paginate(Bucket=bucket, Prefix=prefix):
        for v in page.get('Versions') or []:
            if TEST_KEY_MARKER in v['Key']:
                yield (v['Key'], v['VersionId'])
        for m in page.get('DeleteMarkers') or []:
            if TEST_KEY_MARKER in m['Key']:
                yield (m['Key'], m['VersionId'])


def delete_one(s3, bucket: str, key: str, version_id: str) -> None:
    s3.delete_object(Bucket=bucket, Key=key, VersionId=version_id)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument('--bucket', required=True, help='Resource Data Sync bucket name')
    parser.add_argument('--account-id', required=True)
    parser.add_argument('--region', required=True)
    parser.add_argument('--profile', default='default')
    parser.add_argument('--workers', type=int, default=50)
    parser.add_argument('--dry-run', action='store_true', help='List matching objects but do not delete')
    args = parser.parse_args()

    if not args.account_id.isdigit() or len(args.account_id) != 12:
        print(f'ERROR: --account-id must be a 12-digit number, got {args.account_id!r}', file=sys.stderr)
        sys.exit(1)

    session = boto3.Session(profile_name=args.profile)
    s3 = session.client(
        's3',
        config=Config(max_pool_connections=args.workers + 10, retries={'max_attempts': 3, 'mode': 'adaptive'}),
    )

    print(f'{"DRY RUN: " if args.dry_run else ""}Deleting fake test data from s3://{args.bucket}/AWS:*/accountid={args.account_id}/region={args.region}/...')

    # Collect every matching (key, versionId) across all four inventory
    # prefixes before deleting so the progress count is accurate.
    targets = []
    for inv in INVENTORY_TYPES:
        prefix = f'{inv}/accountid={args.account_id}/region={args.region}/resourcetype=ManagedInstanceInventory/'
        for key, version_id in list_test_object_versions(s3, args.bucket, prefix):
            targets.append((key, version_id))
        print(f'  scanned {inv}: running total {len(targets)} versions to delete')

    if not targets:
        print('Nothing to delete.')
        return

    if args.dry_run:
        for key, version_id in targets[:20]:
            print(f'  would delete: {key} (v={version_id})')
        if len(targets) > 20:
            print(f'  ... and {len(targets) - 20} more')
        print(f'Total: {len(targets)} object versions')
        return

    done = 0
    failed = 0
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        futures = {
            ex.submit(delete_one, s3, args.bucket, key, version_id): (key, version_id)
            for key, version_id in targets
        }
        for fut in as_completed(futures):
            key, version_id = futures[fut]
            try:
                fut.result()
                done += 1
                if done % PRINT_EVERY == 0 or done == len(targets):
                    print(f'  {done}/{len(targets)} versions deleted...', flush=True)
            except Exception as e:
                failed += 1
                print(f'  ERROR deleting {key} (v={version_id}): {e}', file=sys.stderr, flush=True)

    if failed > 0:
        print(f'Done with {failed} failures', file=sys.stderr)
        sys.exit(1)

    print(f'Done. {done} object versions deleted.')


if __name__ == '__main__':
    main()
